exp_config = {'n_epochs': 5000,
              'batch_size': 8,
              'lr': 1e-4,
              'grad_clip_value': None,
              # 'grad_clip_norm': None,
              'grad_clip_norm': 1.,
              'device': 1,
              'comet_config': {'api_key': 'prsuXaz6RVyjfIWmbZwVjWMug',
                               'project_name': 'autoregressive-flows',
                               'workspace': 'joelouismarino'},
}
