exp_config = {'n_epochs': 1e4,
              'batch_size': 8,
              'lr': 1e-4,
              'grad_clip_value': None,
              # 'grad_clip_norm': None,
              'grad_clip_norm': 1.,
              'device': 1,
              'checkpoint_exp_key': None,
              'rest_api_key': 'jHxSNRKAIOSSBP4TyRvGHfanF',
              'checkpoint_interval': 10,
              'comet_config': {'api_key': 'prsuXaz6RVyjfIWmbZwVjWMug',
                               'project_name': 'autoregressive-flows',
                               'workspace': 'joelouismarino'},
}
