data_config = {'dataset_name': 'stochastic_moving_mnist',
               'data_path': '/local-scratch/chenleic/Data',
               'add_noise': True,
               'num_digits': 2,
               'train_epoch_size': 500,
               'val_epoch_size': 100,
               'sequence_length': 13,
               'eval_length': 10,
               'img_hz_flip': False,
               'img_size': 64}
